// <auto-generated />
using System;
using InsuranceWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceWebApp.Migrations
{
    [DbContext(typeof(InsuranceDBContext))]
    [Migration("20260408054609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceWebApp.Models.Client", b =>
                {
                    b.Property<int>("client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("client_id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_Step_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("client_id");

                    b.HasIndex("phone");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Contract", b =>
                {
                    b.Property<int>("contract_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contract_id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("insurance_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("insurance_premium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("contract_id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("client_id");

                    b.HasIndex("employee_id");

                    b.HasIndex("product_id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_Step_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.InsuranceProduct", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insurance_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("max_term_days")
                        .HasColumnType("int");

                    b.Property<int>("min_term_days")
                        .HasColumnType("int");

                    b.Property<decimal>("tariff_rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("product_id");

                    b.ToTable("InsuranceProducts");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.InsuranceSituation", b =>
                {
                    b.Property<int>("situation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("situation_id"));

                    b.Property<DateTime>("claim_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("contract_id")
                        .HasColumnType("int");

                    b.Property<decimal>("damage_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("incident_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("situation_id");

                    b.HasIndex("contract_id");

                    b.HasIndex("employee_id");

                    b.ToTable("InsuranceSituations");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Payment", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("payment_id"));

                    b.Property<decimal>("amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("contract_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("payment_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("payment_id");

                    b.HasIndex("contract_id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Payout", b =>
                {
                    b.Property<int>("payout_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("payout_id"));

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("payout_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("payout_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("situation_id")
                        .HasColumnType("int");

                    b.HasKey("payout_id");

                    b.HasIndex("situation_id");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Contract", b =>
                {
                    b.HasOne("InsuranceWebApp.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("client_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceWebApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsuranceWebApp.Models.InsuranceProduct", "Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.InsuranceSituation", b =>
                {
                    b.HasOne("InsuranceWebApp.Models.Contract", "Contract")
                        .WithMany("Situations")
                        .HasForeignKey("contract_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceWebApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Payment", b =>
                {
                    b.HasOne("InsuranceWebApp.Models.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("contract_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Payout", b =>
                {
                    b.HasOne("InsuranceWebApp.Models.InsuranceSituation", "Situation")
                        .WithMany("Payouts")
                        .HasForeignKey("situation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.Contract", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Situations");
                });

            modelBuilder.Entity("InsuranceWebApp.Models.InsuranceSituation", b =>
                {
                    b.Navigation("Payouts");
                });
#pragma warning restore 612, 618
        }
    }
}
